{
 "title": "p2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "INST_ACTIV_POWER_A_MINUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/INST_ACTIV_POWER_A_MINUS\")"
    }
   ]
  },
  {
   "title": "INST_ACTIV_POWER_A_PLUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/INST_ACTIV_POWER_A_PLUS\")\r\n"
    }
   ]
  },
  {
   "title": "A -",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/A_MINUS\")"
    }
   ]
  },
  {
   "title": "A +",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/A_PLUS\")"
    }
   ]
  },
  {
   "title": "U1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/U1\")\r\n \r\n"
    }
   ]
  },
  {
   "title": "U2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/U2\")\r\n"
    }
   ]
  },
  {
   "title": "U3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/U3\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "I1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/I1\")\r\n"
    }
   ]
  },
  {
   "title": "I2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/I2\")\r\n"
    }
   ]
  },
  {
   "title": "I3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/I3\")"
    }
   ]
  },
  {
   "title": "SWELLS_L1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SWELLS_L1\")"
    }
   ]
  },
  {
   "title": "LONG_FAILURES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/LONG_FAILURES\")"
    }
   ]
  },
  {
   "title": "SAGS_L2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SAGS_L2\")"
    }
   ]
  },
  {
   "title": "SAGS_L3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SAGS_L3\")"
    }
   ]
  },
  {
   "title": "SAGS_L1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SAGS_L1\")"
    }
   ]
  },
  {
   "title": "SWELLS_L3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SWELLS_L3\")"
    }
   ]
  },
  {
   "title": "SWELLS_L2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SWELLS_L2\")"
    }
   ]
  },
  {
   "title": "SHORT_FAILURES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"p1_port_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.topic == \"SX_meter/SHORT_FAILURES\")"
    }
   ]
  }
 ]
}